correspondencias_iso_code3 = {'Bahamas, The' : "BHS",
 'Bolivia' : "BOL",
 'Congo, Democratic Republic of the' : "COD",
 'Congo, Republic of' : "COG", 
 'Czech Republic' : "CZE",
 "Côte d'Ivoire" : "CIV",
 'Gambia, The' : "GMB",
 'Hong Kong SAR' : "HKG",
 'Iran' : "IRN",
 'Korea' : "KOR",
 'Kosovo' : "XKX",
 'Kyrgyz Republic' : "KGZ",
 'Lao P.D.R.' : "LAO",
 'Macao SAR' : "MAC",
 'Macedonia, FYR' : "MKD",
 'Micronesia' : "FSM",
 'Moldova' : "MDA",
 'Montenegro, Rep. of' : "MNE",
 'Russia' : "RUS",
 'Slovak Republic' : "SVK",
 'St. Kitts and Nevis' : "KNA",
 'St. Lucia' : "LCA",
 'St. Vincent and the Grenadines' : "VCT",
 'Syria' : "SYR",
 'São Tomé and Príncipe' : "STP",
 'Taiwan Province of China' : "TWN",
 'Tanzania' : "TZA",
 'Turkey' : "TUR",
 'United Kingdom' : "GBR",
 'United States' : "USA",
 'Venezuela' : "VEN",
 'Vietnam' : "VNM",
 'West Bank and Gaza' : "PSE"}
